-- MySQL Script generated by MySQL Workbench
-- 04/30/15 13:27:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agenda` ;

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`contactos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agenda`.`contactos` ;

CREATE TABLE IF NOT EXISTS `agenda`.`contactos` (
  `nombre` VARCHAR(10) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `telefono` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`telefono`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `agenda`.`contactos`
-- -----------------------------------------------------
START TRANSACTION;
USE `agenda`;
INSERT INTO `agenda`.`contactos` (`nombre`, `apellidos`, `telefono`) VALUES ('aa', 'aa', '1');
INSERT INTO `agenda`.`contactos` (`nombre`, `apellidos`, `telefono`) VALUES ('bb', 'bb', '2');

COMMIT;

